version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chatbot
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - backend-network

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - backend-network

  backend:
    build: .
    container_name: backend
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    ports:
      - "3000:3000"
    networks:
      - backend-network
    command: npm run start:dev

volumes:
  postgres_data:

networks:
  backend-network:
    driver: bridge
